name: CI pipeline

on:
  push:
    branches: [ main, mediapipe, dev ]
  pull_request:
    branches: [ main, mediapie ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: vue-next
      run: npm install

    - name: Run tests
      working-directory: vue-next
      run: npm run test
